### ISSUE TITLE
Doesn’t install on Archlinux

### ISSUE THREAD

**Issue by phaazon** [wearefractal/msi-keyboard#19] opened 2015-04-05 23:04 UTC
```
phaazon@illusion ~/msi-keyboard % npm install --python=python2.7
/
> node-hid@0.3.2 preinstall /home/phaazon/msi-keyboard/node_modules/node-hid
> sh get-hidapi.sh

Cloning into 'hidapi'...
remote: Counting objects: 1965, done.
remote: Total 1965 (delta 0), reused 0 (delta 0), pack-reused 1965
Receiving objects: 100% (1965/1965), 2.79 MiB | 939.00 KiB/s, done.
Resolving deltas: 100% (1082/1082), done.
Checking connectivity... done.

> node-hid@0.3.2 install /home/phaazon/msi-keyboard/node_modules/node-hid
> sh install.sh

make: Entering directory '/home/phaazon/msi-keyboard/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c: In function ‘hid_read_timeout’:
../hidapi/libusb/hid.c:1078:6: warning: variable ‘bytes_read’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
  int bytes_read = -1;
      ^
  AR(target) Release/obj.target/hidapi.a
  COPY Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc: In member function ‘virtual v8::Handle<v8::Value> JSException::asV8Exception() const’:
../src/HID.cc:50:71: error: ‘New’ is not a member of ‘v8::String’
   virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
                                                                       ^
../src/HID.cc:50:101: error: ‘ThrowException’ was not declared in this scope
   virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
                                                                                                     ^
../src/HID.cc: At global scope:
../src/HID.cc:58:1: error: expected class-name before ‘{’ token
 {
 ^
../src/HID.cc:61:38: error: ‘Arguments’ does not name a type
   static Handle<Value> devices(const Arguments& args);
                                      ^
../src/HID.cc:76:34: error: ‘Arguments’ does not name a type
   static Handle<Value> New(const Arguments& args);
                                  ^
../src/HID.cc:77:35: error: ‘Arguments’ does not name a type
   static Handle<Value> read(const Arguments& args);
                                   ^
../src/HID.cc:78:36: error: ‘Arguments’ does not name a type
   static Handle<Value> write(const Arguments& args);
                                    ^
../src/HID.cc:79:36: error: ‘Arguments’ does not name a type
   static Handle<Value> close(const Arguments& args);
                                    ^
../src/HID.cc:80:45: error: ‘Arguments’ does not name a type
   static Handle<Value> setNonBlocking(const Arguments& args);
                                             ^
../src/HID.cc:81:47: error: ‘Arguments’ does not name a type
   static Handle<Value> getFeatureReport(const Arguments& args);
                                               ^
../src/HID.cc:83:48: error: ‘Arguments’ does not name a type
   static Handle<Value> sendFeatureReport(const Arguments& args);
                                                ^
../src/HID.cc:86:25: error: ‘uv_work_t’ has not been declared
   static void recvAsync(uv_work_t* req);
                         ^
../src/HID.cc:87:29: error: ‘uv_work_t’ has not been declared
   static void recvAsyncDone(uv_work_t* req);
                             ^
../src/HID.cc:177:16: error: variable or field ‘recvAsync’ declared void
 HID::recvAsync(uv_work_t* req)
                ^
../src/HID.cc:177:16: error: ‘uv_work_t’ was not declared in this scope
../src/HID.cc:177:27: error: ‘req’ was not declared in this scope
 HID::recvAsync(uv_work_t* req)
                           ^
In file included from ../src/HID.cc:30:0:
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Object]’:
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:592:17:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>; T = v8::Object; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Object>]’
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:5826:21:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Object; M2 = v8::NonCopyablePersistentTraits<v8::Object>; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>]’
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:657:14:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>]’
../src/HID.cc:94:17:   required from here
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:167:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ^
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:596:5: note: in expansion of macro ‘TYPE_CHECK’
     TYPE_CHECK(O, Primitive);
     ^
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Function]’:
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:592:17:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>; T = v8::Function; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Function>]’
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:5826:21:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Function; M2 = v8::NonCopyablePersistentTraits<v8::Function>; T = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>]’
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:657:14:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>]’
../src/HID.cc:94:17:   required from here
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:167:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ^
/home/phaazon/.node-gyp/0.12.2/deps/v8/include/v8.h:596:5: note: in expansion of macro ‘TYPE_CHECK’
     TYPE_CHECK(O, Primitive);
     ^
../src/HID.cc: In member function ‘virtual v8::Handle<v8::Value> JSException::asV8Exception() const’:
../src/HID.cc:50:104: warning: control reaches end of non-void function [-Wreturn-type]
   virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
                                                                                                        ^
HID.target.mk:94: recipe for target 'Release/obj.target/HID/src/HID.o' failed
make: *** [Release/obj.target/HID/src/HID.o] Error 1
make: Leaving directory '/home/phaazon/msi-keyboard/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.2-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "install"
gyp ERR! cwd /home/phaazon/msi-keyboard/node_modules/node-hid
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--python=python2.7"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.3.2 install: `sh install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.3.2 install script 'sh install.sh'.
npm ERR! This is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/phaazon/msi-keyboard/npm-debug.log
```

**Comment by stevelacy** [comment] 2015-04-06 05:39
duplicate of #18

**Closed by stevelacy** 2015-04-06 05:39 UTC
